models/flight_booking_records.py
from app.main import db
from datetime import datetime

class FlightBookingRecords(db.Model):
	__tablename__ = 'flight_booking_records'
	id = db.Column(db.Integer, primary_key = True, autoincrement = True)
	flight_number = db.Column(db.String(100), primary_key = True)
	flight_date = db.Column(db.Date, primary_key = True)
	departure_time = db.Column(db.Time(timezone = False), nullable = False) #departure from the source
	total_seats = db.Column(db.Integer, nullable = False)
	seats_booked = db.Column(db.Integer, default = 0)
	created_on = db.Column(db.DateTime(timezone=False), default=datetime.now(), nullable=False)
	updated_on = db.Column(db.DateTime(timezone=False), default=datetime.now(), nullable=False)

views/booking_information.py
from flask import Blueprint, request, url_for, render_template, redirect, flash
from datetime import datetime
from random import randint

booking_module = Blueprint('booking_information', __name__)

from app.models.user_booking_info import *
from app.models.flightinfo import *
from app.models.flight_booking_records import * 


@booking_module.route('/flight/<flight_no>/availability')
def flight_availability(flight_no):
	flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()

	if not flight_detail:
		flash('There is no flight with Flight Number: ' + str(flight_no))
		return redirect(url_for('flight_information.flights'))

	available_seats = flight_detail.total_seats - flight_detail.booked_seats
	if available_seats > 0:
		return render_template('flight_detail.html', available_seats = available_seats, flight_detail = flight_detail)
	else:
		flash('No seats available!!')
		return render_template('flight_detail.html')


@booking_module.route('/flight/<flight_no>/book')
def book_ticket(flight_no):
	flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()
	if not flight_detail:
		flash('There is no such flight ('+ str(flight_no) +') in the system!')
		return redirect(url_for('flight_information.flights'))
	available_seats = flight_detail.total_seats - flight_detail.booked_seats	
	return render_template('book_ticket.html', flight_no = flight_no, available_seats = available_seats)


@booking_module.route('/confirm_booking/<flight_no>', methods = ['POST'])
def confirm_booking(flight_no):

	contact_email = request.form['email']
	required_seats = int(request.form['required_seats'])

	# For checking if the booking already exists for this user.
	booking_existence = CustomerBooking.query.filter_by(flight_number = flight_no, contact_email = contact_email).first()

	# For getting flight details
	flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()

	available_seats = flight_detail.total_seats - flight_detail.booked_seats

	if available_seats < required_seats:
		flash('Seats required by you are greater than the available seats!')
		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))
	elif (booking_existence):
		flash('The booking already exists for this contact and flight number! Please check the booking details!')
		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))
	else:

		flight_date = flight_detail.flight_date
		departure_time = flight_detail.departure_time
		booking_id = randint(67890, 99999)
		booking_status = "confirmed"
		booking_date = datetime.now()
		booking_update = booking_date

		new_customer_booking = CustomerBooking(flight_number = flight_no,
											contact_email = contact_email,
											flight_date = flight_date,
											departure_time = departure_time,
											seats_booked = required_seats,
											booking_id = booking_id,
											booking_status = booking_status,
											ticket_booked_on = booking_date,
											ticket_booking_updated_on = booking_update)

		db.session.add(new_customer_booking)

		try:
			db.session.commit()
		except Exception, e:
			flash('There was an error in booking the flight. Please contact the site administrator')
		else:
			flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()
			flight_detail.booked_seats += required_seats
			db.session.commit()

			#Checking if Booking records for this flight is available or not.
			flight_booking_record = FlightBookingRecords.query.filter_by(flight_number = flight_no).first()

			if not flight_booking_record:
				# Adding the booking record for flight booking
				booking_record = FlightBookingRecords(flight_number = flight_no,
													flight_date = flight_date,
													departure_time = departure_time,
													total_seats = flight_detail.total_seats,
													seats_booked = flight_detail.booked_seats,
													created_on = booking_date,
													updated_on = booking_update)
				db.session.add(booking_record)
				db.session.commit()
			else:
				flight_booking_record.seats_booked += required_seats
				flight_booking_record.updated_on = datetime.now()
				db.session.commit()

			flash('Booking Confirmed! ' + 'Booking ID is: ' + str(booking_id) + '. Please keep it for future reference.')


		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))


@booking_module.route('/flight/<flight_no>/book/<booking_id>', methods = ['GET', 'POST'])
def get_booking_information(flight_no, booking_id):

	if request.method == 'POST':
		booking_id = request.form['booking_id']

	booking_details = CustomerBooking.query.filter_by(flight_number = flight_no, booking_id = booking_id).first()
	if not booking_details:
		flash('The booking for Flight No. '+ str(flight_no) +' and Booking ID '+ str(booking_id) +' does not exist! OR the flight had been cancelled. Please check if ' + str(flight_no) + ' exists!')
		return render_template('booking_details.html', flight_no = flight_no)
	else:
		return render_template('booking_details.html', booking_details = booking_details)


@booking_module.route('/delete_booking/<flight_no>/<booking_id>', methods = ['GET' ,'DELETE'])
def delete_ticket(flight_no, booking_id):
	cust_booking_details = CustomerBooking.query.filter_by(flight_number = flight_no, booking_id = booking_id).first()
	if not cust_booking_details:
		flash('There is no booking for this flight no. ' + str(flight_no) + ' and booking ID ' + str(booking_id))
		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))

	db.session.delete(cust_booking_details)

	try:
		db.session.commit()
	except Exception, e:
		flash('There was an error deleting the record. Please try again!')
		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))
	else:
		## Update the booked_seats in flight information
		flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()
		if not flight_detail:
			flash('There is no flight with Flight Number : ' + str(flight_no))
			return redirect(url_for('flight_information.flights'))
		flight_detail.booked_seats -= cust_booking_details.seats_booked

		##Update the seats_booked in Flight Booking Records
		db.session.query(FlightBookingRecords).filter_by(flight_number = 
						flight_no).update({FlightBookingRecords.seats_booked: (FlightBookingRecords.seats_booked - cust_booking_details.seats_booked)})

		## Commit the changes to the DB
		db.session.commit()
		

		flash('Booking Details Deleted for booking ID ' + str(booking_id))
		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))
	
	return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))


@booking_module.route('/update_booking/<flight_no>/<booking_id>', methods = ['POST'])
def update_ticket(flight_no, booking_id):
	cust_booking_details = CustomerBooking.query.filter_by(flight_number = flight_no, booking_id = booking_id).first()
	
	if not cust_booking_details:
		flash('There is no booking for this flight no. ' + str(flight_no) + ' and booking ID ' + str(booking_id))
		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))
	flash('Update the booking information for booking ID: ' + str(booking_id))
	return render_template('update_ticket.html', cust_booking_details = cust_booking_details)


@booking_module.route('/update_processing/<flight_no>/<booking_id>', methods = ['POST'])
def update_processing(flight_no, booking_id):

	updated_email = request.form['updated_email']
	released_seats = int(request.form['released_seats'])

	cust_booking_details = CustomerBooking.query.filter_by(flight_number = flight_no, booking_id = booking_id).first()
	
	if not cust_booking_details:
		flash('There is no booking for this flight no. ' + str(flight_no) + ' and booking ID ' + str(booking_id))
		return redirect(url_for('booking_information.book_ticket', flight_no = flight_no))

	if released_seats > cust_booking_details.seats_booked:
		flash('You are trying to release more seats than you have booked. Please try again with a valid number!')
		return render_template('update_ticket.html', cust_booking_details = cust_booking_details)

	if released_seats == cust_booking_details.seats_booked:
		flash('You released all the booked seats. ')
		return redirect(url_for('booking_information.delete_ticket', flight_no = flight_no, booking_id = booking_id))

	## Updating booked seats and contact email in the customer booking information
	cust_booking_details.seats_booked -= released_seats
	cust_booking_details.contact_email = updated_email
	cust_booking_details.ticket_booking_updated_on = datetime.now()


	try:
		db.session.commit()
	except Exception, e:
		flash('There was an error updating the booking information. Please try again later!')
		return render_template('update_ticket.html', cust_booking_details = cust_booking_details)
	else:

		## Updating the booked seats in Flight Information
		flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()
		if not flight_detail:
			flash('This flight with flight number: ' + str(flight_no) + ' does not exist. Please check your booking status for more information.')
			return redirect(url_for('flight_information.flights'))
		flight_detail.booked_seats -= released_seats	

		# updating the booked seats in Flight Booking Records
		db.session.query(FlightBookingRecords).filter_by(flight_number = 
						flight_no).update({FlightBookingRecords.seats_booked: (FlightBookingRecords.seats_booked - released_seats)})

		## Commit the changes to the DB
		db.session.commit()


		## Sending the response to the front end	
		flash(str(released_seats) + ' seats released. ' 'Updated the booking information')
		return redirect(url_for('booking_information.get_booking_information', flight_no = flight_no, booking_id = booking_id))

views/flight_information.py
from flask import Blueprint, request, url_for, render_template, redirect, flash
from flask_login import login_required, current_user
from datetime import datetime

flight_module = Blueprint('flight_information', __name__)

from app.models.flightinfo import * 
from app.models.user_booking_info import *
from app.models.flight_booking_records import *


@flight_module.route('/flights/<admin>')
@flight_module.route('/flights')
def flights(admin = None):

	flights = FlightDetails.query.all()

	if admin == None:
		return render_template('flights.html', flights = flights)
	else:
		return render_template('flights.html', current_user = current_user, flights = flights)


@flight_module.route('/newFlight', methods = ['POST'])
@login_required
def Add_new_flight():

	flight_number = request.form['flight_number']
	source = request.form['source']
	destination = request.form['destination']
	flight_date = request.form['flight_date']
	departure = request.form['departure']
	arrival = request.form['arrival']
	total_seats = request.form['total_seats']
	created_at = datetime.now()
	updated_at = created_at

	new_flight = FlightDetails(flight_number = flight_number, source = source, destination = destination, flight_date = flight_date, 
								departure_time = departure, destination_arrival_time = arrival, 
								total_seats = total_seats, booked_seats = 0, created_at = created_at, updated_at = updated_at)

	db.session.add(new_flight)

	try:
		db.session.commit()
	except Exception, e:
		flash('There was an error in adding a flight. Please contact the site administrator')
	else:
		flash('New Flight Added Successfully')


	return redirect(url_for('flight_information.flights'))


@flight_module.route('/flight/<flight_no>')
def flight_data(flight_no):
	flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()

	return render_template('flight_detail.html', current_user = current_user, flight_detail = flight_detail)


@flight_module.route('/delete_flight/<flight_no>', methods = ['GET' ,'DELETE'])
def delete_flight(flight_no):
	flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()
	if not flight_detail:
		flash('There is no flight with flight no.' + str(flight_no))
		return redirect(url_for('flight_information.flights'))

	db.session.delete(flight_detail)

	try:
		db.session.commit()
	except Exception, e:
		flash('There was an error deleting the flight record. Please try again!')
		return redirect(url_for('flight_information.flights'))
	else:
		db.session.query(CustomerBooking).filter_by(flight_number = flight_no).delete()
		db.session.query(FlightBookingRecords).filter_by(flight_number = flight_no).delete()
		db.session.commit()
		flash('Flight Details Deleted for Flight Number:  ' + str(flight_no) + '. All bookings deleted!!')
		return redirect(url_for('flight_information.flights'))
	
	return redirect(url_for('flight_information.flights'))



@flight_module.route('/update_flight/<flight_no>', methods = ['POST'])
def update_flight(flight_no):
	
	updated_flight_date = request.form['updated_flight_date']
	updated_departure = request.form['updated_departure']
	updated_arrival = request.form['updated_arrival']
	updated_total_seats = int(request.form['updated_total_seats'])

	flight_detail = FlightDetails.query.filter_by(flight_number = flight_no).first()

	if not flight_detail:
		flash('Flight Does not Exist!')
		return redirect(url_for('flight_information.flights'))

	if updated_total_seats < flight_detail.booked_seats:
		flash('Total Seats Cannot be changed to less than already booked!!')
		return redirect(url_for('flight_information.flight_data', flight_no = flight_no))

	flight_detail.flight_date = updated_flight_date
	flight_detail.departure_time = updated_departure
	flight_detail.destination_arrival_time = updated_arrival
	flight_detail.total_seats = updated_total_seats
	flight_detail.updated_at = datetime.now()

	try:
		db.session.commit()
	except Exception, e:
		flash('There was an error updating the flight information. Please try again later!')
		return redirect(url_for('flight_information.flight_data', flight_no = flight_no))
	else:
		## Updating the Customer Booking information based on Modified Flight Details
		db.session.query(CustomerBooking).filter_by(flight_number = flight_no).update({CustomerBooking.flight_date:flight_detail.flight_date,
																						CustomerBooking.departure_time:flight_detail.departure_time })
		
		## Updating the Flight Booking records based on Modified Flight Details
		db.session.query(FlightBookingRecords).filter_by(flight_number = flight_no).update({FlightBookingRecords.total_seats: flight_detail.total_seats,
																							FlightBookingRecords.flight_date: flight_detail.flight_date,
																							FlightBookingRecords.departure_time: flight_detail.departure_time,
																							FlightBookingRecords.updated_on: datetime.now() })
		## Commit changes to the DB
		db.session.commit()

		flash('Updated the flight information for Flight No. ' + str(flight_no))
		return redirect(url_for('flight_information.flight_data', flight_no = flight_no))

	return redirect(url_for('flight_information.flight_data', flight_no = flight_no))


@flight_module.route('/<flight_no>/booking_records')
@login_required
def booking_records(flight_no):
	flight_booking_records = FlightBookingRecords.query.filter_by(flight_number = flight_no)
	return render_template('flight_booking_records.html', current_user = current_user, flight_booking_records = flight_booking_records)

views/index.py
from flask import Blueprint, request, url_for, render_template, redirect, flash
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from app.main import login_manager

index_module = Blueprint('index', __name__)

from app.models.admin import * 


login_manager.login_view = '/' #this works with @login_required decorator
login_manager.login_message = 'You need to log in with correct credentials!'


## mapping the python flask object with the object in the actual model
@login_manager.user_loader
def load_user(user_id):
	uid = Admin.query.get(user_id)
	return uid


@index_module.route('/')
def index():
	return render_template('index.html')



@index_module.route('/login', methods = ['POST'])
def admin_login():
	username = request.form['username']
	password = request.form['password']

	admin = Admin.query.filter_by(username = username).first()

	if not admin:
		flash('User Not Found! Please contact the Airlines\' Support Center')
		return redirect(url_for('index.index'))
	elif admin.password != password:
		flash('Invalid Credentials!')
		return redirect(url_for('index.index'))
	else:
		login_user(admin)
		return redirect(url_for('flight_information.flights', admin = current_user.username))



@index_module.route('/logout')
@login_required
def admin_logout():
	logout_user()
	flash('Successfully Logged Out!')
	return redirect(url_for('index.index'))

templates/book_ticket.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<title>Flight Management System</title>
</head>

<body>
	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">Flight Management System</a>
	    </div>
	  </div>
	</nav> <!-- Brand Navbar end -->

	<div class="container">
	{% with messages = get_flashed_messages() %}
	  	{% if messages %}
	    		<br />
			{% for message in messages %}
				<p class="flashes"><strong>{{ message }}</strong></p>
			{% endfor %}
	    		
	   	{% endif %}
	{% endwith %}		
		
	</div>	


	<div class="container">
	  <!-- Form -->
	  <form action=" {{url_for('booking_information.confirm_booking', flight_no = flight_no) }} " method="POST">
	    <div class="form-group">
	      <label for="email">Contact Email</label>
	      <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
	    </div>  
	      
	    <div class="form-group">
	      <label for="required_seats">No. of Seats Required? (Available Seats: {{ available_seats }})</label>
	      <input type="number" class="form-control" name="required_seats" id="required_seats" placeholder="Required Seats" required>
	    </div>	

	    <button type="submit" class="btn btn-primary">Submit</button>
	  </form>

	  <br />

		<a href=" {{ url_for('flight_information.flights') }} "><button class="btn btn-primary">Cancel Booking / Back to All Flights</button></a>	  

	</div>

	<div class="container">
		<br /><br /><h4>OR</h4> <p>Track your booking status for this flight.</p> <br/>
	</div>

	<div class="container">
        <form class="form-inline" action=" {{ url_for('booking_information.get_booking_information', flight_no = flight_no, booking_id = 'None') }} " method="POST">
            <div class="form-group">
              <label for="booking_id">Booking ID</label>
              <input type="text" class="form-control" name="booking_id" id="booking_id" placeholder="Booking ID" required>
            </div>

		  <button type="submit" class="btn btn-primary">Get Booking Information</button>
		</form>

	</div>	


</body>

</html>

templates/flight_booking_records.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<title>Flight Management System</title>
</head>

<body>
	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">Flight Management System</a>
	    </div>
	  </div>
	</nav> <!-- Brand Navbar end -->


	<div class="container">
		<a href=" {{ url_for('flight_information.flights') }} "><button class="btn btn-primary">Back to All Flights</button></a>
	</div>	

	<br />

	<div class="container">
		<table border="2" width="100%">
			
		<thead>
			<th>Flight No.</th>
			<th>Flight Date</th>
			<th>Departure Time</th>
			<th>Total Seats</th>
			<th>Booked Seats</th>
		</thead>
			{% if flight_booking_records %}
				{% for record in flight_booking_records %}
				<tr>
					<td> {{ record.flight_number }} </td>
					<td> {{ record.flight_date }} </td>
					<td> {{ record.departure_time }} </td>
					<td> {{ record.total_seats }} </td>
					<td> {{ record.seats_booked }} </td>
				</tr>
				{% endfor %}
			{% endif %}
		</table>

	</div>


</body>

</html>

templates/flights.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<title>Flight Management System</title>
</head>

<body>
	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">Flight Management System</a>
	    </div>
	  </div>
	</nav> <!-- Brand Navbar end -->

	<div class="container">
		{% if current_user.username %}
			<h2> Welcome {{ current_user.username }}
			<a href="{{ url_for('index.admin_logout') }}"><button class="btn btn-primary">Logout!</button></a>
			</h2>

			<a href="#" data-toggle="modal" data-target="#add_flight"><button class="btn btn-primary">Add a New Flight</button></a>


		{% endif %}

	</div>

	<div class="container">
	{% with messages = get_flashed_messages() %}
	  	{% if messages %}
	    		
			{% for message in messages %}
				<br /><p class="flashes"><strong>{{ message }}</strong></p>
			{% endfor %}
	    		
	   	{% endif %}
	{% endwith %}		
		
	</div>	

	<br />

	<div class="container">
		<table border="2" width="100%">
			
		<thead>
			<th>Flight No.</th>
			<th>Source</th>
			<th>Destination</th>
			<th>Flight Date</th>
			<th>Departure Time</th>
			<th>Arrival at Destination</th>
		</thead>
			{% if flights %}
				{% for flight in flights %}
				<tr>
					<td><a href=" {{ url_for('flight_information.flight_data', flight_no = flight.flight_number) }} "> {{ flight.flight_number }} </a></td>
					<td> {{ flight.source }} </td>
					<td> {{ flight.destination }} </td>
					<td> {{ flight.flight_date }} </td>
					<td> {{ flight.departure_time }} </td>
					<td> {{ flight.destination_arrival_time }} </td>
					<td> <a href=" {{ url_for('booking_information.flight_availability', flight_no = flight.flight_number) }} ">Check Availability & Book Seats</a> </td>
					{% if current_user %}
						<td> <a href=" {{ url_for('flight_information.booking_records', flight_no = flight.flight_number) }} ">Check Booking Records</a> </td>
					{% endif %}
				</tr>
				{% endfor %}
			{% endif %}
		</table>

	</div>


      <!-- Modal for adding new flight information -->
        <div class="modal fade" id="add_flight" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add a New Flight</h4>
              </div>
              <div class="modal-body text-left">
                  
                  <!-- Form -->
                  <form action=" {{url_for('flight_information.Add_new_flight') }} " method="POST">
                    <div class="form-group">
                      <label for="flight_number">Flight Number</label>
                      <input type="text" class="form-control" name="flight_number" id="flight_number" placeholder="Flight Number" required>
                    </div>  
                      
                    <div class="form-group">
                      <label for="source">Source</label>
                      <input type="text" class="form-control" name="source" id="source" placeholder="Source" required>
                    </div>

                    <div class="form-group">
                      <label for="destination">Destination</label>
                      <input type="text" class="form-control" name="destination" id="destination" placeholder="Destination" required>
                    </div> 
                    
                    <div class="form-group">
                      <label for="flight_date">Flight Date (YYYY-MM-DD)</label>
                      <input type="date" class="form-control" name="flight_date" id="flight_date"required>
                    </div>       

                    <div class="form-group">
                      <label for="departure">Departure Time (HH:MM)</label>
                      <input type="time" class="form-control" name="departure" id="departure" required>
                    </div> 

                    <div class="form-group">
                      <label for="arrival">Destination Arrival Time (HH:MM)</label>
                      <input type="time" class="form-control" name="arrival" id="arrival" required>
                    </div> 

                    <div class="form-group">
                      <label for="total_seats">Total Seats (Number)</label>
                      <input type="number" class="form-control" name="total_seats" id="total_seats" placeholder="Total Seats on flight" required>
                    </div> 
                                                                         
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                    
                  </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>



<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>

</html>

templates/index.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<title>Flight Management System</title>
</head>

<body>
	<nav class="navbar navbar-inverse">
	  <div class="container">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">Flight Management System</a>
	    </div>
	  </div>
	</nav> <!-- Brand Navbar end -->

	<div class="container">
		<button class="btn btn-primary" onclick="login_form()">Admin Login</button>
		<a href=" {{ url_for('flight_information.flights') }} "><button class="btn btn-primary">Book a flight</button></a>
	</div>

	<div class="container" id="admin_login" style="display: none">
		<form action=" {{url_for('index.admin_login') }} " method="POST">
        	UserName: <br />
        	<input type="text" class="form-control" name="username" placeholder = "UserName" /><br />
        	Password: <br />
        	<input type="password" class="form-control" name="password" placeholder = "Password" /><br />
        	<input type="submit" class="btn btn-primary" value="Login">
    	</form>		
	</div>

	<div class="container">
	{% with messages = get_flashed_messages() %}
	  	{% if messages %}
	    		
			{% for message in messages %}
				<br /><p class="flashes"><strong>{{ message }}</strong></p>
			{% endfor %}
	    		
	   	{% endif %}
	{% endwith %}		
		
	</div>

<script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>

</html>